### ISSUE TITLE
Ledger hardware wallet is not supported

### ISSUE THREAD

**Issue by valo** [mosendo/gasless.js#3]
Seems like the library uses the `signTypedMessage` method, which is currently not supported by hardware wallets like Ledger. See https://github.com/MetaMask/metamask-extension/pull/5792

The error that is received upon trying to sign the message:

`MetaMask - RPC Error: MetaMask Message Signature: Error: Not supported on this device`

I am wondering if it's possible to use a different type of signature, so that hardware wallets can be supported. This problem will be a significant obstacle in implementing the gasless system for a mainstream usage.

**Comment by nourharidy** [comment]
Unfortunately, EIP712's signTypedData is required by the MCD DAI contract.

That being said, it may be possible to use [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine) to construct an intermediate web3 provider and support signTypedData by creating a provider middleware which would use Ledger's plain signatures to construct signTypedData signatures.
